name: Hello MLOps

on:
  push:
    branches: [main]

jobs:
  train-simulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install numpy scikit-learn

      - name: Run training script
        run: python train.py
